{{- if not .Values.existingSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autodelete-discord.fullname" . }}-config
  labels:
    {{- include "autodelete-discord.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}
{{- end }}